#!/bin/sh
# Copyright 2021 Jack Everley

[ -n "$INTERFACE" ] || exit 0

[ "$ACTION" = ifup ] && {
    /etc/init.d/wanmonitor stop "$INTERFACE"
    if ! /etc/init.d/wanmonitor enabled || [ "$(uci -q get "wanmonitor.$INTERFACE.enabled")" != 1 ]; then
        exit 0
    fi

    logger -t wanmonitor "Starting wanmonitor due to $ACTION of $INTERFACE ($DEVICE)"

    if /etc/init.d/sqm enabled >/dev/null 2>&1; then
        ingressDevice=$(uci -q get "wanmonitor.$INTERFACE.ingressDevice")
        if [ -n "$ingressDevice" ] && [ "$ingressDevice" != "$DEVICE" ]; then
            /usr/lib/sqm/run.sh stop "$ingressDevice" >/dev/null 2>&1
            /usr/lib/sqm/run.sh start "$ingressDevice" >/dev/null 2>&1
        fi
    fi

    lua /usr/sbin/wanmonitor.lua -i "$INTERFACE" 2>>/tmp/wanmonitor.error
}

[ "$ACTION" = ifdown ] && {
    /etc/init.d/wanmonitor stop "$INTERFACE"

    local ingressDevice=$(uci -q get "wanmonitor.$INTERFACE.ingressDevice")
    if [ -n "$ingressDevice" ] && [ "$ingressDevice" != "$DEVICE" ]; then
        /usr/lib/sqm/run.sh stop "$ingressDevice" >/dev/null 2>&1
    fi
}
