#!/bin/sh
# Copyright 2021 Jack Everley

[ -n "$INTERFACE" ] || exit 0

[ "$ACTION" = ifup ] && {
    /etc/init.d/wanmonitor stop "${INTERFACE}"
    /etc/init.d/wanmonitor enabled && /etc/init.d/wanmonitor start "${INTERFACE}"
}

[ "$ACTION" = ifdown ] && {
    /etc/init.d/wanmonitor stop "${INTERFACE}"
}
