#!/bin/sh /etc/rc.common
# Copyright 2021 Jack Everley

START=50

interfaces() {
	if [ -n "$(echo $@)" ]; then
		echo $@
		return
	fi
	echo $(ubus list network.interface.* | sed 's/network\.interface\.//')
}

stop() {
	for i in $(interfaces $@); do
		if [ -f "/var/run/wanmonitor.$i.pid" ]; then
			local pid=$(cat "/var/run/wanmonitor.$i.pid")
			[ -n "$pid" ] && kill -15 "$pid" 2>/dev/null
			rm -f "/var/run/wanmonitor.$i.pid"
		fi
		rm -f "/var/wanmonitor.$i.json"
	done
}

start() {
	for i in $(interfaces $@); do
		stop "$i"
		[ "$(uci -q get "wanmonitor.$i.enabled")" = 1 ] || continue

		if [ "$(uci -q get "wanmonitor.$i.autorate")" = 1 ] && /etc/init.d/sqm enabled >/dev/null 2>&1; then
			local device=$(ubus call "network.interface.$i" status 2>/dev/null | jsonfilter -q -e '@.l3_device')
			if [ -n "$device" ]; then
				/usr/lib/sqm/run.sh stop "$device" >/dev/null 2>&1
				/usr/lib/sqm/run.sh start "$device" >/dev/null 2>&1
			fi

			local ingressDevice=$(uci -q get "wanmonitor.$i.ingressDevice")
			if [ -n "$ingressDevice" ] && [ "$ingressDevice" != "$device" ]; then
				/usr/lib/sqm/run.sh stop "$ingressDevice" >/dev/null 2>&1
				/usr/lib/sqm/run.sh start "$ingressDevice" >/dev/null 2>&1
			fi
		fi
		lua /usr/sbin/wanmonitor.lua -i "$i" 2>>/tmp/wanmonitor.error
	done
}

boot() {
	exit 0
}
