#!/bin/sh /etc/rc.common
# Copyright 2021 Jack Everley

START=50

interfaces() {
	if [ -n "$(echo $@)" ]; then
		echo $@
		return
	fi
	echo $(ubus list network.interface.* | sed 's/network\.interface\.//')
}

stop() {
	for i in $(interfaces $@); do
		if [ -f "/var/run/wanmonitor.$i.pid" ]; then
			local pid=$(cat "/var/run/wanmonitor.$i.pid")
			kill -15 "$pid" 2>/dev/null
			rm -f "/var/run/wanmonitor.$i.pid"
		fi
		rm -f "/var/wanmonitor.$i.json"
	done
}

start() {
	for i in $(interfaces $@); do
		stop "$i"
		lua /usr/sbin/wanmonitor.lua -i "$i"
	done
}

boot() {
	exit 0
}
